version: '3.8'

services:
  # 1. docker-main (Nginx)
  service-docker-main:
    image: yeadoh/nginx:1.29.7-docker-main
    container_name: docker-main-container
    restart: always
    ports:
      - "8080:80"
    networks:
      - board-network

  # 2. docker-install (Nginx)
  service-docker-install:
    image: yeadoh/nginx:1.29.7-docker-install
    container_name: docker-install-container
    restart: always
    ports:
      - "8081:80"
    networks:
      - board-network

  # 3. docker-command (Nginx)
  service-docker-command:
    image: yeadoh/nginx:1.29.7-docker-command
    container_name: docker-command-container
    restart: always
    ports:
      - "8082:80"
    networks:
      - board-network

  # 4. docker-build (Nginx)
  service-docker-build:
    image: yeadoh/nginx:1.29.7-docker-build
    container_name: docker-build-container
    restart: always
    ports:
      - "8083:80"
    networks:
      - board-network

  # 5. docker-compose (Nginx)
  service-docker-compose:
    image: yeadoh/nginx:1.29.7-docker-compose
    container_name: docker-compose-container
    restart: always
    ports:
      - "8084:80"
    networks:
      - board-network

  # 6. docker-swarm (Nginx)
  service-docker-swarm:
    image: yeadoh/nginx:1.29.7-docker-swarm
    container_name: docker-swarm-container
    restart: always
    ports:
      - "8085:80"
    networks:
      - board-network
  
  # 7. kubernetes (FastAPI)
  service-kubernetes:
    image: yeadoh/fastapi:kubernetes
    container_name: kubernetes-fastapi-container
    restart: always
    ports:
      - "8001:80"
    networks:
      - board-network

  # 08-1. board-main (Nginx)
  service-board-main:
    image: yeadoh/nginx:1.29.7-board-main
    container_name: board-main-container
    restart: always
    ports:
      - "8086:80"
    networks:
      - board-network

  # 08-2. board-fastapi (FastAPI)
  service-board-fastapi:
    image: yeadoh/fastapi:3.11-board
    container_name: board-fastapi-container
    restart: always
    depends_on:
      - service-board-database
    environment:
      DB_HOST: service-board-database
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 3306
    ports:
      - "8002:8000"
    networks:
      - board-network

  # 08-3. board-database (MySQL)
  service-board-database:
    image: yeadoh/mysql:8.0-board
    container_name: board-database-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8003:3306"
    networks:
      - board-network

networks:
  board-network:
    driver: bridge